### PR TITLE
add url support

### PR DESCRIPTION
**Pull request by l3thal**
I've added support for urls and suppressed the final output unless verbose. 
Now results can be displayed for each utterance as they are received. 
I realize this may be out of scope for this app, but it adds a nice touch if being used in a 
"real-time" fashion. With ffmpeg you can give it just about any type of file, or even live stream, and decode it on the fly.

### CODE REVIEW

**Comment by taf2** [comment]
this is very cool feature.  i'm trying it out and will very likely merge it in.  curious how are you using the gem?

**Comment by ylluminate** [comment]
Wow, how fantastic!

**Comment by ylluminate** [comment]
Can you show us an example of where you've leveraged this so as to see this in context and full glory of its potential use case?

**Comment by l3thal** [comment]
@ylluminate 
I guess a potential use case would be to display real-time results while transcribing a large audio/video file.

**Comment by ylluminate** [comment]
Right, sorry, I was just thinking of seeing it "in action."  But yes, absolutely.  I'm really curious about performance and efficiency while watching the traffic flow / packet size.

**Comment by l3thal** [comment]
Honestly, speech modeling is not as easy as it seems and Google has the resources everyone else isn't as fortunate to have access too. That being said, I am taking advantage of Google's work while I have the chance hahaha. It is an undocumented, unpublished api so there are no guarantees how long it will be available, but I dont think it is going to disappear overnight ;)

**Comment by ylluminate** [comment]
Well, the advantage of leaving this open is that they get a potential large amount of extra speech to work with so as to refine their algorithms.  I think this is primarily why it is left hanging open.

**Comment by l3thal** [comment]
Oh, of course. They are benefiting from leaving it open as much as we are using it.

**Pull request merged**
